name: Ubuntu
on:
    push:
        paths-ignore:
            - ".vscode/**"
            - "**.md"
            - ".gitignore"

permissions:
    contents: read

jobs:
    build:
        name: Build
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                cc: [clang, gcc]
                os: [ubuntu-22.04]

        steps:
            - name: Clone repository
              uses: actions/checkout@v3
              
            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y ninja-build ${{ matrix.cc }}
              
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: "3.10"
                
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install meson~=1.0.0
                
            - name: Build
              run: |
                meson setup builddir
                meson compile -C builddir
                  
            - name: Test
              run: meson test -C builddir
