name: Ubuntu
on:
    push:
        paths-ignore:
            - ".vscode/**"
            - "**.md"
            - ".gitignore"

permissions:
    contents: read

jobs:
    build:
        name: Build
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                cc: [clang, gcc]
                os: [ubuntu-22.04]

        steps:
            - name: Clone repository
              uses: actions/checkout@v3
              
            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y ninja-build clang-format ${{ matrix.cc }}
              
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: "3.10"
                
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install meson~=1.0.0

            - name: Setup build dir
              run: CC=${{ matrix.cc }} meson setup builddir

            - name: Check formatting
              continue-on-error: true
              run: ninja clang-format-check -C builddir
                
            - name: Build
              run: meson compile -C builddir
                  
            - name: Test
              id: test
              run: meson test -C builddir

            - name: Upload testlog
              uses: actions/upload-artifact@v3
              # if: failure() && steps.test.outcome == 'failure'
              with:
                name: testlog-${{matrix.os}}-${{matrix.cc}}.txt
                path: builddir/meson-logs/testlog.txt
